

```{r}
library(readr)
library(ggplot2)
library(dplyr)
ad_org_train <- read_csv("~/Desktop/ad_org/ad_org_train.csv")
ad <- ad_org_train
ad_org_test <- read_csv("~/Desktop/ad_org/ad_org_test.csv")
#Remove extra charactor
ad$duration <- sub(pattern = "PT", replacement = "", x = ad$duration)
#Hour
ad$hour <- sub(pattern = "([0-9]+)H.*$","\\1", x = ad$duration)
ad$hour <- as.integer(ad$hour)
#Minut
#1 remove Hours
ad$minuts <- sub(pattern = ".*([0-9]+)H","", x = ad$duration)
ad$sec <- sub(pattern = ".*([0-9]+)M","", x = ad$minuts)
#Get Minuts
ad$minuts <- sub(pattern = "([0-9]+)M.*$","\\1", x = ad$minuts)
ad$minuts <- as.integer(ad$minuts)
#Get seconds
ad$sec <- sub(pattern = "([0-9]+)S","\\1", x = ad$sec)
ad$sec <- as.integer(ad$sec)

ad[is.na(ad)] <- 0
sum(is.na(ad$adview))
sum(is.na(ad$views))
sum(is.na(ad$likes))
sum(is.na(ad$dislikes))
sum(is.na(ad$comment))
sum(is.na(ad$category))
#actual length of the video in sec colname: len
ad <- ad %>% mutate(minlen = round(((hour*3600)+(minuts*60)+(sec))/60,2)) %>% select(-minuts, -hour, -sec, -duration, -vidid, -published)

#chage the classes of likes dislike and comment as numeric & category
ad$category <- as.factor(ad$category)
ad$comment <- round(as.numeric(ad$comment),0)
ad$likes <- round(as.numeric(ad$likes),0)
ad$dislikes <- round(as.numeric(ad$dislikes),0)


#Features creation,raios View vs likes/dislikes/comments
ad$likesratio <- as.integer(round((ad$views / ad$likes),0))
ad$dislikesratio <- as.integer(round((ad$views / ad$dislikes),0))
ad$commentratio <- as.integer(round((ad$views / ad$comment),0))


```

```{r}
#Selection of appropriate data for training a model
ad <- ad[ad$adview<50,]
ad <- ad[ad$likesratio<3000 & !is.na(ad$likesratio),]
sum(ad$dislikesratio<15000, na.rm = TRUE)
ad <- ad[ad$dislikesratio<20000 & !is.na(ad$dislikesratio),]
ad <- ad[!is.na(ad$comment),]
#ggplot(ad, aes(y = adview, x = dislikesratio)) + geom_point()
#ggplot(ad, aes(y = adview, x = likesratio)) + geom_point()
```

```

